name: "Shairport Sync on Home Assistant OS"
description: >
  Start Shairport Sync on Home Assistant OS utilizing a local audio device
version: "1.0.0"
slug: "shairport-sync-rpi"

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

startup: application
host_network: true

devices:
  - /dev/snd

options:
  airplay_name: "homeassistant"

schema:
  airplay_name: str
